# -*- coding: utf-8 -*-
"""calculator2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qOPfrnMpez6_NLdL2LXbfAz1JweVll57
"""

import math

print("\t\t****Calculator*****")

a=input("Enter 1st number: ")
b=input("Enter 2nd number: ")

op=input("Enter operation to perform: (+,-,*,/,**,%,trigo)\n")
if (op=="+") :
    print(float(a)+float(b))
elif (op== "-"):
    print(float(a)-float(b))
elif (op=="*"):
    print(float(a)*float(b))
elif (op=="/"):
    print(float(a)/float(b))
elif (op== "**") :
    print(float(a)** float(b))
elif (op== "%") :
    print( float(a)% float(b))

elif(op== "trigo"):
  op2 = input("Function: (sin,cos,tan)")
  if (op2=="sin") :
    print (math.sin(math.radians(int(a))+math.radians(int(b))))
  elif (op2=="cos") :
    print (math.cos(math.radians(int(a))+math.radians(int(b))))
  elif (op2=="tan") :
    print (math.tan(math.radians(int(a))+math.radians(int(b))))

op2 = input("Function: (sin,cos,tan)")
if (op2=="sin") :
    print (math.sin(math.radians(int(a))+math.radians(int(b))))